receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  otlp:
    endpoint: "http://jaeger:4318"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
