apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdr-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cdr-service
  template:
    metadata:
      labels:
        app: cdr-service
    spec:
      containers:
        - name: cdr-service
          image: cdr-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/cdrdb
            - name: SPRING_DATASOURCE_USERNAME
              value: user
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
